### PR TITLE
Style heading to be more integrative

### PR DESCRIPTION
**Pull request by Hammster**
The current heading looked a little bit out of place and was not aligning well with Atom. 
So i tweaked it a little bit.

exampleview

### CODE REVIEW

**Comment by jccguimaraes** [comment]
this looks awesome! Just give me until later in the night to do some necessary changes on the contribution list and apply it in the `refactor` branch for the `0.3.0`release!

**Comment by jccguimaraes** [comment]
don't mind the travis integration by the way...

**Comment by Hammster** [comment]
Thanks awesome to hear

**Comment by jccguimaraes** [comment]
Just merged, published in Atom and added you as a contributor in the [refactor README.md](https://github.com/jccguimaraes/atom-project-viewer/blob/refactor/README.md)

**Pull request merged**
