### PR TITLE
Fix for horizontal scrollbar

### PR DESCRIPTION
**Pull request by bitkris-dev**
You could see an horizontal scrollbar all the time. That's now fixed
changing the list item width to 90% instead of 100%, otherwise the
margin-left activates the overflow-x.

### CODE REVIEW

**Comment by jccguimaraes** [comment]
Hi @bitkris-dev,

Thanks for the contribution.
Could you just do 2 things?

1. Add a **before/after** preview of this because i have an OSX and ain't seeing this issue (maybe Win/Linux probably have this).
2. Add yourself in the `.all-contributorsrc` :haircut_man: 

Thanks and well spotted!

**Comment by bitkris-dev** [comment]
Sure, no problem! That's the screenshot:
beforeafter

**Comment by jccguimaraes** [comment]
@bitkris-dev can you do me a favor?

**Comment by bitkris-dev** [comment]
@jccguimaraes Sure, just ask! :)

**Comment by jccguimaraes** [comment]
can you checkout branch `1.0.0` and see if this issue still occurs?
Keep in mind a lot is changing :).

It won't mess with your current db file but, for the sake of it, just backup it.

Would appreciate it :+1:

**Comment by bitkris-dev** [comment]
Unfortunately, the branch 1.0.0 doesn't work at all. (In fact, I have also noticed that Travis CI wasn't successfull on the build).

Those are the errors appearing:

screenshot 27

**Comment by jccguimaraes** [comment]
you need to `npm install` :)

**Comment by jccguimaraes** [comment]
yeah, but maybe the css files will brake due to being in win :(

**Comment by jccguimaraes** [comment]
Also all can't create anything right now through the plugin... you need to copy the `spec/mocks/project-viewer.json`to wherever the `atom.getConfigDirPath()` gives you...

**Comment by bitkris-dev** [comment]
Ops, sorry! I'm new to atom package development.
I've correctly installed the new 1.0.0 version, but the first notification said "No local database found". So it isn't able to detect previous database and projects. I've tried to open other settings, clicking on "Import from Gist" or any other menu item, **nothing** happens. I don't know why it looks like broken on my machine.

Uninstalling it and reinstalling the official apm version restored my previous projects. So I can confirm you it doesn't screw up the database, it's only unable to read the previous one.

**Comment by jccguimaraes** [comment]
yeah, was too slow on giving you instructions :( read my comments above. I will push some changes in a minute for ease

**Comment by bitkris-dev** [comment]
Ok, I've followed your instructions. Now this is what appears to me:

15d5785c8e5053b1ac4f0c4bc8c2b66a

As you can see, no more horizontal scrollbar! For the rest, it's the same, all the menu items don't work. Also, right-clicking the fake projects doesn't do anything, I can't edit them.

Trying to open them gives me this error:

f6ba1621ce47074404092abd06e6b948

But I suppose it's just a matter of wrong directory.

If you have other requests, feel free to contact me again whenever you want. Glad to help :)

**Comment by jccguimaraes** [comment]
hey @bitkris-dev,
sorry for late replying, was feeling sick.
Well, it is supposed not to work mostly anything :) i am in the process of a major refactor in the editor viewer. You can check the progress by `Menu -> Project Viewer -> Open editor`. But it is only UI for now. (that error is normal, but fixed also)

Regarding the version, it is intended that way, because when publishing in Atom, it will bump the version up!

**Comment by bitkris-dev** [comment]
It makes sense :) nice!

**Pull request merged**
